# Generated by Django 4.2.7 on 2023-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_healthcareprovider_email_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='fees',
            field=models.IntegerField(default=1200),
        ),
    ]
