# Generated by Django 4.2.7 on 2023-11-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_healthcareprovider_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(default=""),
        ),
    ]
