# Generated by Django 4.2.7 on 2023-11-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_remove_healthcareprovider_email_remove_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField()),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.healthcareprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescheduled_datetime', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ImageField(upload_to='')),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.healthcareprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user')),
            ],
        ),
    ]
