# Generated by Django 4.2.7 on 2023-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.TextField(default='Something wrong with my health'),
        ),
    ]
