# Generated by Django 4.2.7 on 2023-11-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_appointment_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RescheduleHistory',
        ),
    ]
