# Generated by Django 4.2.7 on 2023-11-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_delete_reschedulehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
