# Generated by Django 4.2.7 on 2023-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_remove_appointment_id_appointment_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
