# Generated by Django 4.2.7 on 2023-11-19 17:29

import Records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0005_remove_appointment_app_id_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarerecord',
            name='report',
            field=models.ImageField(upload_to=Records.models.healthcare_record_image_path),
        ),
    ]
