# Generated by Django 4.2.7 on 2023-11-26 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0006_alter_healthcarerecord_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcarerecord",
            name="report",
        ),
    ]
