# Generated by Django 4.2.7 on 2023-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0007_remove_healthcarerecord_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcarerecord",
            name="report",
            field=models.FileField(default="pdfs/default.pdf", upload_to="pdfs/"),
        ),
    ]
